### ISSUE TITLE
系统突然更新，需要上传健康码了😓

### ISSUE THREAD

**Issue by GamingInJail** [xiaotianxt/PKU-SIMSO-FREE#1]
原来的自动程序无法直接提交了，全部卡在“已保存”，得手动多上传一个健康码截图，simso才允许提交

**Comment by xiaotianxt** [comment]
> 原来的自动程序无法直接提交了，全部卡在“已保存”，得手动多上传一个健康码截图，simso才允许提交

dev 分支上已经给了一个上传图片的接口，我在思考怎么解决比较合适。大家有啥想法吗🤔

现在园区往返提交材料其实不需要审核，所以我在考虑，过渡时间，要不要直接传一个空二进制文件得了😂
