### ISSUE TITLE
simso日常新增功能😂（是否抵京7日）

### ISSUE THREAD

**Issue by GamingInJail** [xiaotianxt/PKU-SIMSO-FREE#4]
如题，出入校又新添了“是否抵京已满7日”这么个选项，申请又会卡在这一步不能自动提交。
日常新增表单域，堪称与洞主作对了哈哈哈哈

**Comment by xiaotianxt** [comment]
> 如题，出入校又新添了“是否抵京已满7日”这么个选项，申请又会卡在这一步不能自动提交。
> 
> 日常新增表单域，堪称与洞主作对了哈哈哈哈

👌回去就加上

**Comment by GamingInJail** [comment]
好欸！
