### ISSUE TITLE
fake image upload

### ISSUE THREAD

**Issue by TobiasLee** [xiaotianxt/PKU-SIMSO-FREE#5]
感觉传二进制假图有潜在风险 能在repo里搞个上传健康宝图片（可能是过期的）就好啦

**Comment by TobiasLee** [comment]
anyway，感谢老哥的脚本， 方便的话可以放个二维码请你喝杯奶茶 lol

**Comment by xiaotianxt** [comment]
> anyway，感谢老哥的脚本， 方便的话可以放个二维码请你喝杯奶茶 lol

心意我领啦 😄

> 感觉传二进制假图有潜在风险 能在repo里搞个上传健康宝图片（可能是过期的）就好啦

现在似乎不需要上传图片了，我把 fake_img 去掉了。
